# This section declares settings for the database.
[database]

# The database for caching, support Redis only:
#   redis://<user>:<password>@<host>:<port>/<db_number>
cache_store = "redis://redis:6379"

# The database for persist data, support MySQL, Postgres, ClickHouse and MongoDB:
#   mysql://[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
#   postgres://bob:secret@1.2.3.4:5432/mydb?sslmode=verify-full
#   clickhouse://user:password@host[:port]/database?param1=value1&...&paramN=valueN
#   mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
data_store = "mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true"

# The cache size for recommended/popular/latest items. The default value is 100.
cache_size = 200

# Insert new users while inserting feedback. The default value is true.
auto_insert_user = true

# Insert new items while inserting feedback. The default value is true.
auto_insert_item = true

# The feedback types for positive events.
positive_feedback_types = ["star","like","favorite","text","call","map","share"]

# The feedback types for read events.
read_feedback_types = ["read", "view"]

# The time-to-live (days) of positive feedback, 0 means disabled. The default value is 0.
positive_feedback_ttl = 0

# The time-to-live (days) of items, 0 means disabled. The default value is 0.
item_ttl = 0

# This section declares settings for the master node.
[master]
port = 8086                     # master port
host = "0.0.0.0"                # master host
http_port = 8088                # HTTP API port
http_host = "0.0.0.0"           # HTTP API host
n_jobs = 4                      # number of working jobs
meta_timeout = 10               # cluster meta timeout (second)

# This section declares settings for the server node.
[server]
default_n = 20                  # default number of returned items
api_key = ""                    # secret key for RESTful APIs (SSL required)

# This section declares settings for recommendation.
[recommend]

# The time window of popular items (days). The default values is 180.
popular_window = 30

# The time period for model fitting (minutes). The default values is 60.
fit_period = 60

# The time period for model searching (minutes). The default values is 100.
search_period = 100

# The number of epochs for model searching. The default values is 100.
search_epoch = 100

# The number of trials for model searching. The default values is 10.
search_trials = 10

# The time period to refresh recommendation for inactive users (days). The default values is 5.
refresh_recommend_period = 1

# The fallback recommendation method is used when cached recommendation drained out:
#   item_based: Recommend similar items to cold-start users.
#   popular: Recommend popular items to cold-start users.
#   latest: Recommend latest items to cold-start users.
# Recommenders are used in order. The default values is ["latest"].
fallback_recommend = ["item_based", "latest", "popular"]

# The type of neighbors for items. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common users.
#   auto: If a item have labels, neighbors are found by number of common labels.
#         If this item have no labels, neighbors are found by number of common users.
# The default values is "auto".
item_neighbor_type = "auto"

# The type of neighbors for users. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common liked items.
#   auto: If a user have labels, neighbors are found by number of common labels.
#         If this user have no labels, neighbors are found by number of common liked items.
# The default values is "auto".
user_neighbor_type = "auto"

# Enable latest recommendation during offline recommendation. The default values is false.
enable_latest_recommend = true

# Enable popular recommendation during offline recommendation. The default values is false.
enable_popular_recommend = true

# Enable user-based similarity recommendation during offline recommendation. The default values is false.
enable_user_based_recommend = true

# Enable item-based similarity recommendation during offline recommendation. The default values is false.
enable_item_based_recommend = true

# Enable collaborative filtering recommendation during offline recommendation. The default values is true.
enable_collaborative_recommend = true

# Enable click-though rate prediction during offline recommendation. Otherwise, results from multi-way recommendation
# would be merged randomly. The default values is true.
enable_click_through_prediction = true

# The explore recommendation method is used to inject popular items or latest items into recommended result:
#   popular: Recommend popular items to cold-start users.
#   latest: Recommend latest items to cold-start users.
# Recommenders are used in order. The default values is { popular = 0.0, latest = 0.0 }.
explore_recommend = { popular = 0.1, latest = 0.2 }
