default_context:
  project_name: 'Mahao Backend'
  project_slug: 'mahao'
  domain_main: 'mahao.com'
  domain_staging: 'stag.mahao.com'
  docker_swarm_stack_name_main: 'mahao-com'
  docker_swarm_stack_name_staging: 'stag-mahao-com'
  secret_key: '6a694845a0fe08f39949ba3664212c40096f4eda4d2c6e3b6b50b10eaf5f3cb7'
  first_superuser: 'admin@mahao.com'
  first_superuser_password: 'Maroon2015'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mahao.com", "https://stag.mahao.com", "https://mahao.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mahao.com'
  postgres_password: 'Maroon2015'
  pgadmin_default_user: 'admin@mahao.com'
  pgadmin_default_user_password: 'Maroon2015'
  traefik_constraint_tag: 'mahao.com'
  traefik_constraint_tag_staging: 'stag.mahao.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Maroon2015'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
