"""Add last update field to all models

Revision ID: 151032ac960f
Revises: 47e56b7f167e
Create Date: 2021-12-30 14:04:45.506828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151032ac960f'
down_revision = '47e56b7f167e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenity', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('favorite', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('feedback', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('property', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('propertyamenity', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('propertycategory', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('propertyphoto', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_updated')
    op.drop_column('propertyphoto', 'last_updated')
    op.drop_column('propertycategory', 'last_updated')
    op.drop_column('propertyamenity', 'last_updated')
    op.drop_column('property', 'last_updated')
    op.drop_column('feedback', 'last_updated')
    op.drop_column('favorite', 'last_updated')
    op.drop_column('amenity', 'last_updated')
    # ### end Alembic commands ###
