"""Add PropertyAmenity table

Revision ID: 2f736666b56e
Revises: 3a2a60c70a8e
Create Date: 2021-12-29 10:43:38.518523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f736666b56e'
down_revision = '3a2a60c70a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propertyamenity',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'amenity_id')
    )
    op.create_index(op.f('ix_propertyamenity_amenity_id'), 'propertyamenity', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_propertyamenity_property_id'), 'propertyamenity', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propertyamenity_property_id'), table_name='propertyamenity')
    op.drop_index(op.f('ix_propertyamenity_amenity_id'), table_name='propertyamenity')
    op.drop_table('propertyamenity')
    # ### end Alembic commands ###
