"""Add feature_image to property

Revision ID: 3a2a60c70a8e
Revises: fff6fa88a70a
Create Date: 2021-12-28 21:16:41.715087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2a60c70a8e'
down_revision = 'fff6fa88a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('feature_image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'feature_image')
    # ### end Alembic commands ###
