"""Add Property Photo table

Revision ID: 47e56b7f167e
Revises: b287e0d34201
Create Date: 2021-12-29 17:30:50.762655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e56b7f167e'
down_revision = 'b287e0d34201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propertyphoto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propertyphoto_id'), 'propertyphoto', ['id'], unique=False)
    op.create_index(op.f('ix_propertyphoto_property_id'), 'propertyphoto', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propertyphoto_property_id'), table_name='propertyphoto')
    op.drop_index(op.f('ix_propertyphoto_id'), table_name='propertyphoto')
    op.drop_table('propertyphoto')
    # ### end Alembic commands ###
