"""Add property category

Revision ID: c90cfb4b04f8
Revises: d4ef9fc37bb3
Create Date: 2021-12-27 16:41:53.915182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c90cfb4b04f8'
down_revision = 'd4ef9fc37bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propertycategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propertycategory_id'), 'propertycategory', ['id'], unique=False)
    op.create_index(op.f('ix_propertycategory_title'), 'propertycategory', ['title'], unique=True)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_propertycategory_title'), table_name='propertycategory')
    op.drop_index(op.f('ix_propertycategory_id'), table_name='propertycategory')
    op.drop_table('propertycategory')
    # ### end Alembic commands ###
